// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXMR2lHvEUnjedC_-Ng2mX6O8uFwOrUEA',
    appId: '1:525960322699:web:3b507eda471d23a1d3be8e',
    messagingSenderId: '525960322699',
    projectId: 'rankit-78bb2',
    authDomain: 'rankit-78bb2.firebaseapp.com',
    storageBucket: 'rankit-78bb2.appspot.com',
    measurementId: 'G-M6H2VPV3FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNkBSFyKNCD5_UxqqflW77DST_UAQaqV0',
    appId: '1:525960322699:android:b4dfbabedf71a7ffd3be8e',
    messagingSenderId: '525960322699',
    projectId: 'rankit-78bb2',
    storageBucket: 'rankit-78bb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAICMtTIM_JZcFSuBkvSGRraKZM1IgTA2s',
    appId: '1:525960322699:ios:3df861afdfbe7f66d3be8e',
    messagingSenderId: '525960322699',
    projectId: 'rankit-78bb2',
    storageBucket: 'rankit-78bb2.appspot.com',
    iosBundleId: 'com.example.rankitFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAICMtTIM_JZcFSuBkvSGRraKZM1IgTA2s',
    appId: '1:525960322699:ios:3df861afdfbe7f66d3be8e',
    messagingSenderId: '525960322699',
    projectId: 'rankit-78bb2',
    storageBucket: 'rankit-78bb2.appspot.com',
    iosBundleId: 'com.example.rankitFlutter',
  );
}
