success_criteria = [
    "Does work that has a positive impact on other people",
    "Is on track for a secure retirement",
    "Is financially independent from others",
    "Is a parent",
    "Enjoys their work",
    "Is debt-free",
    "Is enjoyable to be around",
    "Has a purpose in life",
    "Is actively involved in their community",
    "Has strong ethical values",
    "Is recognized as a leader in their profession",
    "Owns a home",
    "Rarely, if ever, worries about money",
    "Makes time for themselves",
    "Has a certification in a skilled trade (e.g., electrician, plumber, mechanic)",
    "Is in a committed relationship",
    "Has close friends to depend on",
    "Is always learning new things",
    "Sets and achieves goals",
    "Prioritizes needs of others above their own",
    "Is consistently advancing in their career",
    "Is in good mental health",
    "Is creative",
    "Is able to manage stress and adversity",
    "Has enough savings to pay for a $500 unexpected expense",
    "Is very knowledgeable regardless of formal education",
    "Determines own work schedule",
    "Has a job that involves managing other people",
    "Feels that their work is valued",
    "Is rich",
    "Regularly sees family members",
    "Is a primary caregiver (e.g., of children, elderly, others in need of care)",
    "Has stable full-time employment",
    "Is married",
    "Is focused on their spiritual wellbeing",
    "Is charitable",
    "Is authentic",
    "Owns a business",
    "Is considered trustworthy by others",
    "Is a kind person",
    "Is in good physical health",
    "Maintains boundaries between work and personal life",
    "Does manual labor, skilled trades, or blue-collar work",
    "Is sought after for good advice",
    "Does work that is intellectually stimulating",
    "Is responsible for making important decisions at work",
    "Has mastered a difficult skill",
    "Goes on vacation regularly",
    "Has a higher standard of living than peers",
    "Has a high school diploma or GED",
    "Regularly sees close friends",
    "Has an advanced degree (e.g., PhD, MD, JD, MBA)",
    "Does managerial, computer-based, or white-collar work",
    "Has a 4-year bachelor's degree",
    "Knows a lot of influential people",
    "Has a high-status job",
    "Is considered physically attractive",
    "Is a graduate of an elite college or university",
    "Is famous",
    "Has a large social media following",
    "Owns a lot of luxury items"
]